### ISSUE TITLE
Need cleanup in App.jsx

### ISSUE THREAD

**Issue by vj-abishek** [vj-abishek/airdrop#18]
Task:
 > Go to `src/App.jsx`
 > There is a comment known as `Clean this when complete`
 > Need to delete the below-given files.

**Comment by Nithin005** [comment]
assign it to me

**Comment by Nithin005** [comment]
thx

**Comment by vj-abishek** [comment]
@Nithin005 there may be similar files. Only delete those files mentioned there. After deleting those file, remove the 3 lines below the comment.
